//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public Nullable<System.DateTime> Time { get; set; }
        public string Action { get; set; }
        public int MemberId { get; set; }
    }
}
